name: Get App Token
description: Gets an app install token for a GitHub app registered in your repository

inputs:
  application-id:
    description: GitHub app ID
    required: true
  application-private-key:
    description: GitHub app private key
    required: true

outputs:
  app-token:
    description: The app token

runs:
  using: node20
  main: dist/index.js
