name: Test action

on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_token
        uses: microsoftgraph/get-app-token@main
        with:
          application-id: ${{ secrets.APPLICATION_ID }}
          application-private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Use token
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.get_token.outputs.app-token }}
          script: |
            const repo = await github.rest.repos.get(context.repo);
            console.log(JSON.stringify(repo, null, 2));
